[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seed_register"
description = "Seed the register database collection."
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["pydantic>=2.5.2,<2.6.0", "motor==3.6.0"]
