apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: stats
            - name: MARIADB_USER
              value: creo
            - name: MARIADB_PASSWORD
              value: creopassword
            - name: MARIADB_ROOT_PASSWORD
              value: creopassword
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: monitoring
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: creo-monitor
  namespace: monitoring
  labels:
    app: creo-monitor
spec:
  selector:
    matchLabels:
      name: creo-monitor
  template:
    metadata:
      labels:
        name: creo-monitor
        app: creo-monitor
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: mysql:8
          command:
            - sh
            - -c
            - |
              until mysqladmin ping -h mariadb.monitoring.svc.cluster.local -u creo -pcreopassword --silent; do
                echo "Waiting for MariaDB..."
                sleep 5
              done
      containers:
        - name: creo-monitor
          image: lubasyannik/creo-monitor:1.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: DATABASE_URL
              value: mysql://creo:creopassword@mariadb.monitoring.svc.cluster.local:3306/stats
            - name: HOST_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: root-fs
              mountPath: /rootfs
              readOnly: true
            - name: var-run-containerd
              mountPath: /var/run/containerd
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: root-fs
          hostPath:
            path: /
        - name: var-run-containerd
          hostPath:
            path: /var/run/containerd
---
apiVersion: v1
kind: Service
metadata:
  name: creo-monitor-svc
  namespace: monitoring
spec:
  selector:
    app: creo-monitor
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
