import_path: invoice-create
description: "Inserts a given invoice into a MongoDB collection."
is_async: true
returns: true
depends_on:
  - name: db:mongo
    init: seed-invoice
signature:
  function: createInvoice
  parameters:
    - arg: 0
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              item:
                type: object
                properties:
                  price_in_cents:
                    type: integer
                    minimum: 0
                    maximum: 1000000
                    exclusiveMaximum: false
                    exclusiveMinimum: true
                  name:
                    type: string
                    minLength: 1
                    maxLength: 128
                additionalProperties: false
                required:
                  - price_in_cents
                  - name
              quantity:
                type: integer
                minimum: 0
                maximum: 10000
                exclusiveMinimum: true
            additionalProperties: false
            required:
              - item
              - quantity
        billing_address:
          type: object
          properties:
            first_name:
              type: string
              minLength: 2
              maxLength: 64
            last_name:
              type: string
              minLength: 2
              maxLength: 64
            street:
              type: string
              minLength: 2
              maxLength: 128
            number:
              type: integer
              minimum: 0
              maximum: 10000
              exclusiveMinimum: true
            zip_code:
              type: integer
              minimum: 1000
              maximum: 99999
            city:
              type: string
              minLength: 3
              maxLength: 64
            country:
              type: string
              minLength: 3
              maxLength: 64
          additionalProperties: false
          required:
            - first_name
            - last_name
            - street
            - number
            - zip_code
            - city
            - country
        shipping_address:
          type: object
          properties:
            first_name:
              type: string
              minLength: 2
              maxLength: 64
            last_name:
              type: string
              minLength: 2
              maxLength: 64
            street:
              type: string
              minLength: 2
              maxLength: 128
            number:
              type: integer
              minimum: 0
              maximum: 10000
              exclusiveMinimum: true
            zip_code:
              type: integer
              minimum: 1000
              maximum: 99999
            city:
              type: string
              minLength: 3
              maxLength: 64
            country:
              type: string
              minLength: 3
              maxLength: 64
          additionalProperties: false
          required:
            - first_name
            - last_name
            - street
            - number
            - zip_code
            - city
            - country
        user_id:
          type: string
          minLength: 10
          maxLength: 24
        extra_info:
          type: string
          minLength: 0
          maxLength: 512
        invoice_number:
          type: string
          minLength: 10
          maxLength: 13
      additionalProperties: false
      required:
        - items
        - billing_address
        - shipping_address
        - user_id
        - extra_info
        - invoice_number
