programming_language: rust
application: profile-rust
ssh_config:
  key_file: ~/.ssh/id_ed25519
  master_hosts:
    - 1.1.1.1
  worker_hosts:
    - 2.2.2.2
  user_name: creo
benchmark:
  rps:
    - 25
    - 75
    - 150
  iterations: 5
  benchmark_duration: 900
  virtual_users: 450
  warmup_pause: 10
  warmup_duration: 120
  warmup_rps: 10
  timeout: 8000
  records: 3000000
