import_path: login
description: "Login a user using username/email and password authentication."
is_async: true
returns: true
depends_on:
  - name: db:mongo
    init: seed-login
signature:
  function: loginWithUsernameOrEmail
  parameters:
    - arg: 0
      type: string
      minLength: 3
      maxLength: 64
    - arg: 1
      type: string
      minLength: 6
      maxLength: 48
